a tohle ?

name: "Auto-cleanup photocustomer.json"

on:
  schedule:
    - cron: "0 1 * * *"  # každý den v 1:00 ráno
  workflow_dispatch:      # umožní ruční spuštění

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read photocustomer.json and remove old entries
        id: clean
        run: |
          file="photocustomer.json"
          echo "Čištění souboru $file..."
          now=$(date +%s)
          tmp=$(mktemp)
          # Uchová pouze záznamy mladší než 24h
          jq "[.[] | select(.datum != null and ((($now - ( (try (fromdateiso8601?(.datum) // 0)) )) < 86400)))]" "$file" > "$tmp"
          mv "$tmp" "$file"

      - name: Commit and push if changes detected
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add photocustomer.json
            git commit -m "🧹 Auto-cleanup photocustomer.json (older than 24 h removed)"
            git push
          else
            echo "Žádné staré záznamy k odstranění."
          fi
